import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import Navbar from "~/components/navbar";
import { cn } from "~/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(inter.className, roboto.variable)}>
      <body>
        <Navbar />
        <main className="px-4 py-8 relative">{children}</main>
      </body>
    </html>
  );
}
